version: '3.7'

volumes:
    logs:
        driver: local
    my-db:
services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db
        ports:
            - 9191:80
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: root
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'chatapp'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'root'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'root'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted
        volumes:
            - my-db:/var/lib/mysql
    slim:
        image: daijie/php7-alpine
        working_dir: /var/www
        command: php -S 127.0.0.1:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
